/*
# Telerrehabilitation App Schema

## Overview
Creates the data model for a telerrehabilitation platform with two user roles:
- Fisioterapeuta (physiotherapist): signs up with email/password, manages patients
- Paciente (patient): accesses via a unique access token generated by a fisio

## New Tables
1. `physiotherapists` — profile for fisio users (linked to auth.users)
   - id (uuid, PK, references auth.users)
   - full_name (text)
   - email (text, unique)
   - university (text) — institution of graduation
   - created_at (timestamptz)
2. `patients` — patients managed by a fisio
   - id (uuid, PK)
   - physio_id (uuid, FK to physiotherapists, ON DELETE CASCADE)
   - full_name (text)
   - age (int)
   - condition (text) — clinical condition/diagnosis
   - notes (text)
   - created_at (timestamptz)
3. `access_tokens` — unique access tokens for patients
   - id (uuid, PK)
   - token (text, unique) — 6-8 char alphanumeric code
   - patient_id (uuid, FK to patients, ON DELETE CASCADE)
   - physio_id (uuid, FK to physiotherapists)
   - is_active (boolean, default true)
   - used_at (timestamptz, nullable) — first login timestamp
   - created_at (timestamptz)
4. `routines` — therapy routines assigned by fisio to patients
   - id (uuid, PK)
   - patient_id (uuid, FK to patients, ON DELETE CASCADE)
   - physio_id (uuid, FK to physiotherapists)
   - title (text)
   - description (text)
   - exercises (jsonb) — array of exercise definitions
   - day_of_week (int) — 0-6 target day
   - created_at (timestamptz)
5. `sessions` — completed therapy sessions by patients
   - id (uuid, PK)
   - patient_id (uuid, FK to patients, ON DELETE CASCADE)
   - routine_id (uuid, FK to routines, nullable)
   - completed_exercises (int)
   - total_exercises (int)
   - duration_minutes (int)
   - score (int) — gamification score
   - created_at (timestamptz)

## Security (RLS)
- physiotherapists: owner-scoped CRUD (auth.uid() = id)
- patients: fisio owns them (physio_id -> physiotherapists.id = auth.uid())
- access_tokens: fisio can CRUD their tokens; patients (anon via token) can read their own token row
- routines: fisio owns via patient ownership
- sessions: fisio can read their patients' sessions; anon can insert (patient submits via token)

## Notes
1. Fisio auth uses Supabase email/password (auth.users). On signup, a physiotherapists row is created.
2. Patient auth is token-based: the patient enters a token, the app looks up the access_tokens table,
   validates is_active, and creates a local session. The anon key is used for patient reads.
3. access_tokens SELECT is open to anon so patients can look up their token; INSERT/UPDATE/DELETE
   restricted to the owning fisio.
*/

-- physiotherapists
CREATE TABLE IF NOT EXISTS physiotherapists (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  email text UNIQUE NOT NULL,
  university text NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE physiotherapists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_physio" ON physiotherapists;
CREATE POLICY "select_own_physio" ON physiotherapists FOR SELECT
  TO authenticated USING (auth.uid() = id);
DROP POLICY IF EXISTS "insert_own_physio" ON physiotherapists;
CREATE POLICY "insert_own_physio" ON physiotherapists FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "update_own_physio" ON physiotherapists;
CREATE POLICY "update_own_physio" ON physiotherapists FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "delete_own_physio" ON physiotherapists;
CREATE POLICY "delete_own_physio" ON physiotherapists FOR DELETE
  TO authenticated USING (auth.uid() = id);

-- patients
CREATE TABLE IF NOT EXISTS patients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  physio_id uuid NOT NULL REFERENCES physiotherapists(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  age int,
  condition text,
  notes text,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_patients" ON patients;
CREATE POLICY "select_own_patients" ON patients FOR SELECT
  TO authenticated USING (physio_id = auth.uid());
DROP POLICY IF EXISTS "insert_own_patients" ON patients;
CREATE POLICY "insert_own_patients" ON patients FOR INSERT
  TO authenticated WITH CHECK (physio_id = auth.uid());
DROP POLICY IF EXISTS "update_own_patients" ON patients;
CREATE POLICY "update_own_patients" ON patients FOR UPDATE
  TO authenticated USING (physio_id = auth.uid()) WITH CHECK (physio_id = auth.uid());
DROP POLICY IF EXISTS "delete_own_patients" ON patients;
CREATE POLICY "delete_own_patients" ON patients FOR DELETE
  TO authenticated USING (physio_id = auth.uid());

-- access_tokens
CREATE TABLE IF NOT EXISTS access_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text UNIQUE NOT NULL,
  patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  physio_id uuid NOT NULL REFERENCES physiotherapists(id) ON DELETE CASCADE,
  is_active boolean NOT NULL DEFAULT true,
  used_at timestamptz,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE access_tokens ENABLE ROW LEVEL SECURITY;

-- anon can SELECT to look up a token (patient login); fisio can select their own
DROP POLICY IF EXISTS "select_tokens" ON access_tokens;
CREATE POLICY "select_tokens" ON access_tokens FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "insert_own_tokens" ON access_tokens;
CREATE POLICY "insert_own_tokens" ON access_tokens FOR INSERT
  TO authenticated WITH CHECK (physio_id = auth.uid());
DROP POLICY IF EXISTS "update_own_tokens" ON access_tokens;
CREATE POLICY "update_own_tokens" ON access_tokens FOR UPDATE
  TO authenticated USING (physio_id = auth.uid()) WITH CHECK (physio_id = auth.uid());
DROP POLICY IF EXISTS "delete_own_tokens" ON access_tokens;
CREATE POLICY "delete_own_tokens" ON access_tokens FOR DELETE
  TO authenticated USING (physio_id = auth.uid());

-- routines
CREATE TABLE IF NOT EXISTS routines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  physio_id uuid NOT NULL REFERENCES physiotherapists(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  exercises jsonb NOT NULL DEFAULT '[]'::jsonb,
  day_of_week int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE routines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_routines" ON routines;
CREATE POLICY "select_routines" ON routines FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "insert_own_routines" ON routines;
CREATE POLICY "insert_own_routines" ON routines FOR INSERT
  TO authenticated WITH CHECK (physio_id = auth.uid());
DROP POLICY IF EXISTS "update_own_routines" ON routines;
CREATE POLICY "update_own_routines" ON routines FOR UPDATE
  TO authenticated USING (physio_id = auth.uid()) WITH CHECK (physio_id = auth.uid());
DROP POLICY IF EXISTS "delete_own_routines" ON routines;
CREATE POLICY "delete_own_routines" ON routines FOR DELETE
  TO authenticated USING (physio_id = auth.uid());

-- sessions
CREATE TABLE IF NOT EXISTS sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  routine_id uuid REFERENCES routines(id) ON DELETE SET NULL,
  completed_exercises int NOT NULL DEFAULT 0,
  total_exercises int NOT NULL DEFAULT 0,
  duration_minutes int NOT NULL DEFAULT 0,
  score int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_sessions" ON sessions;
CREATE POLICY "select_sessions" ON sessions FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "insert_sessions" ON sessions;
CREATE POLICY "insert_sessions" ON sessions FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "update_own_sessions" ON sessions;
CREATE POLICY "update_own_sessions" ON sessions FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM patients p WHERE p.id = sessions.patient_id AND p.physio_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM patients p WHERE p.id = sessions.patient_id AND p.physio_id = auth.uid())
  );
DROP POLICY IF EXISTS "delete_own_sessions" ON sessions;
CREATE POLICY "delete_own_sessions" ON sessions FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM patients p WHERE p.id = sessions.patient_id AND p.physio_id = auth.uid())
  );

-- Indexes
CREATE INDEX IF NOT EXISTS idx_patients_physio ON patients(physio_id);
CREATE INDEX IF NOT EXISTS idx_tokens_token ON access_tokens(token);
CREATE INDEX IF NOT EXISTS idx_tokens_patient ON access_tokens(patient_id);
CREATE INDEX IF NOT EXISTS idx_routines_patient ON routines(patient_id);
CREATE INDEX IF NOT EXISTS idx_sessions_patient ON sessions(patient_id);
